# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

env:
  DOCKER_REGISTRY: "docker.elastic.co"
  VAULT_PATH: "kv/ci-shared/observability-ingest/cloud/gcp"
  ASDF_MAGE_VERSION: 1.14.0
  ASDF_GOLANG_VERSION: 1.22.6
  ASDF_TERRAFORM_VERSION: 1.9.3

steps:
  # - label: "Integration tests: packaging"
  #   key: "package-it"
  #   command: ".buildkite/scripts/steps/integration-package.sh"
  #   artifact_paths:
  #     - build/distributions/**
  #   agents:
  #     provider: "gcp"
  #     machineType: "n1-standard-8"

  # - label: "Integration tests: stateful ESS"
  #   key: test-tf
  #   # depends_on:
  #   #   - package-it
  #   command: |
  #     echo "~~~ Downloading elastic-agent artifacts"
  #     buildkite-agent artifact download build/distributions/** . --step 'package-it' --build 0190bb9a-7d42-41d6-99b8-68dc4309c28b
  #     ls -lah build/distributions/
  #     .buildkite/scripts/steps/integration_tests_tf.sh
  #   artifact_paths:
  #     - build/**
  #   agents:
  #     provider: "gcp"
  #     imageProject: elastic-images-qa
  #     machineType: "n1-standard-8"
  #     # image: "family/platform-ingest-elastic-agent-ubuntu-2204"
  #     image: "platform-ingest-elastic-agent-ubuntu-2404-1722342513"

  - label: "Stateful IT: Ubuntu-default-sudo"
    key: stateful-ubuntu-default-sudo
    # depends_on:
    #   - package-it
    command: |
      buildkite-agent artifact download build/distributions/** . --step 'package-it' --build 0190bb9a-7d42-41d6-99b8-68dc4309c28b
      ls -lah build/distributions/
      .buildkite/scripts/steps/integration_tests_tf_sudo.sh "default" "^(TestAPMConfig|TestDiagnosticsOptionalValues|TestIsolatedUnitsDiagnosticsOptionalValues|TestDiagnosticsCommand|TestIsolatedUnitsDiagnosticsCommand|TestEventLogFile|TestFakeComponent|TestFakeIsolatedUnitsComponent|TestOtelFileProcessing|TestOtelLogsIngestion|TestOtelAPMIngestion|TestPackageVersion)$$"
    artifact_paths:
      - build/**
    agents:
      provider: "gcp"
      imageProject: elastic-images-qa
      machineType: "n1-standard-8"
      # image: "family/platform-ingest-elastic-agent-ubuntu-2204"
      image: "platform-ingest-elastic-agent-ubuntu-2404-1722342513"

  - label: "Stateful IT: Ubuntu-upgrade-sudo"
    key: stateful-ubuntu-upgrade-sudo
    # depends_on:
    #   - package-it
    command: |
      buildkite-agent artifact download build/distributions/** . --step 'package-it' --build 0190bb9a-7d42-41d6-99b8-68dc4309c28b
      ls -lah build/distributions/
      .buildkite/scripts/steps/integration_tests_tf_sudo.sh "upgrade" "^(TestUpgradeBrokenPackageVersion|TestStandaloneUpgradeWithGPGFallback|TestStandaloneUpgradeWithGPGFallbackOneRemoteFailing|TestStandaloneUpgradeRollback|TestStandaloneUpgradeRollbackOnRestarts|TestStandaloneUpgradeFailsWhenUpgradeIsInProgress|TestStandaloneUpgradeRetryDownload|TestStandaloneUpgradeSameCommit|TestStandaloneUpgrade|TestStandaloneUpgradeUninstallKillWatcher)$$"
    artifact_paths:
      - build/**
    agents:
      provider: "gcp"
      imageProject: elastic-images-qa
      machineType: "n1-standard-8"
      # image: "family/platform-ingest-elastic-agent-ubuntu-2204"
      image: "platform-ingest-elastic-agent-ubuntu-2404-1722342513"

  - label: "Stateful IT: Ubuntu-fleet-sudo"
    key: stateful-ubuntu-fleet-sudo
    # depends_on:
    #   - package-it
    command: |
      buildkite-agent artifact download build/distributions/** . --step 'package-it' --build 0190bb9a-7d42-41d6-99b8-68dc4309c28b
      ls -lah build/distributions/
      .buildkite/scripts/steps/integration_tests_tf_sudo.sh "fleet" "^(TestLongRunningAgentForLeaks|TestDelayEnroll|TestDelayEnrollUnprivileged|TestInstallAndCLIUninstallWithEndpointSecurity|TestInstallAndUnenrollWithEndpointSecurity|TestInstallWithEndpointSecurityAndRemoveEndpointIntegration|TestEndpointSecurityNonDefaultBasePath|TestEndpointSecurityUnprivileged|TestEndpointSecurityCannotSwitchToUnprivileged|TestEndpointLogsAreCollectedInDiagnostics|TestForceInstallOverProtectedPolicy|TestSetLogLevelFleetManaged|TestLogIngestionFleetManaged|TestMetricsMonitoringCorrectBinaries|TestEndpointAgentServiceMonitoring|TestMonitoringPreserveTextConfig|TestMonitoringLivenessReloadable|TestComponentBuildHashInDiagnostics|TestProxyURL|TestFleetManagedUpgradeUnprivileged)$$"
    artifact_paths:
      - build/**
    agents:
      provider: "gcp"
      imageProject: elastic-images-qa
      machineType: "n1-standard-8"
      # image: "family/platform-ingest-elastic-agent-ubuntu-2204"
      image: "platform-ingest-elastic-agent-ubuntu-2404-1722342513"

  - label: "Stateful IT: Ubuntu-fqdn-sudo"
    key: stateful-ubuntu-fqdn-sudo
    # depends_on:
    #   - package-it
    command: |
      buildkite-agent artifact download build/distributions/** . --step 'package-it' --build 0190bb9a-7d42-41d6-99b8-68dc4309c28b
      ls -lah build/distributions/
      .buildkite/scripts/steps/integration_tests_tf_sudo.sh "fqdn" "^(TestFQDN)$$"
    artifact_paths:
      - build/**
    agents:
      provider: "gcp"
      imageProject: elastic-images-qa
      machineType: "n1-standard-8"
      # image: "family/platform-ingest-elastic-agent-ubuntu-2204"
      image: "platform-ingest-elastic-agent-ubuntu-2404-1722342513"

  - label: "Stateful IT: Ubuntu-deb-sudo"
    key: stateful-ubuntu-deb-sudo
    # depends_on:
    #   - package-it
    command: |
      buildkite-agent artifact download build/distributions/** . --step 'package-it' --build 0190bb9a-7d42-41d6-99b8-68dc4309c28b
      ls -lah build/distributions/
      .buildkite/scripts/steps/integration_tests_tf_sudo.sh "deb" "^(TestDebLogIngestFleetManaged|TestDebFleetUpgrade)$$"
    artifact_paths:
      - build/**
    agents:
      provider: "gcp"
      imageProject: elastic-images-qa
      machineType: "n1-standard-8"
      # image: "family/platform-ingest-elastic-agent-ubuntu-2204"
      image: "platform-ingest-elastic-agent-ubuntu-2404-1722342513"

  - label: "Stateful IT: Ubuntu-fleet-airgapped-sudo"
    key: stateful-ubuntu-fleet-airgapped-sudo
    # depends_on:
    #   - package-it
    command: |
      buildkite-agent artifact download build/distributions/** . --step 'package-it' --build 0190bb9a-7d42-41d6-99b8-68dc4309c28b
      ls -lah build/distributions/
      .buildkite/scripts/steps/integration_tests_tf_sudo.sh "fleet-airgapped" "^(TestFleetAirGappedUpgradeUnprivileged)$$"
    artifact_paths:
      - build/**
    agents:
      provider: "gcp"
      imageProject: elastic-images-qa
      machineType: "n1-standard-8"
      # image: "family/platform-ingest-elastic-agent-ubuntu-2204"
      image: "platform-ingest-elastic-agent-ubuntu-2404-1722342513"

  - label: "Stateful IT: Ubuntu-fleet-privileged-sudo"
    key: stateful-ubuntu-fleet-privileged-sudo
    # depends_on:
    #   - package-it
    command: |
      buildkite-agent artifact download build/distributions/** . --step 'package-it' --build 0190bb9a-7d42-41d6-99b8-68dc4309c28b
      ls -lah build/distributions/
      .buildkite/scripts/steps/integration_tests_tf_sudo.sh "fleet-privileged" "^(TestInstallFleetServerBootstrap|TestFleetManagedUpgradePrivileged)$$"
    artifact_paths:
      - build/**
    agents:
      provider: "gcp"
      imageProject: elastic-images-qa
      machineType: "n1-standard-8"
      # image: "family/platform-ingest-elastic-agent-ubuntu-2204"
      image: "platform-ingest-elastic-agent-ubuntu-2404-1722342513"

  - label: "Stateful IT: Ubuntu-fleet-airgapped-privileged-sudo"
    key: stateful-ubuntu-fleet-airgapped-privileged-sudo
    # depends_on:
    #   - package-it
    command: |
      buildkite-agent artifact download build/distributions/** . --step 'package-it' --build 0190bb9a-7d42-41d6-99b8-68dc4309c28b
      ls -lah build/distributions/
      .buildkite/scripts/steps/integration_tests_tf_sudo.sh "fleet-airgapped-privileged" "^(TestFleetAirGappedUpgradePrivileged)$$"
    artifact_paths:
      - build/**
    agents:
      provider: "gcp"
      imageProject: elastic-images-qa
      machineType: "n1-standard-8"
      # image: "family/platform-ingest-elastic-agent-ubuntu-2204"
      image: "platform-ingest-elastic-agent-ubuntu-2404-1722342513"

  # - label: "Serverless integration test"
  #   key: "serverless-integration-tests"
  #   concurrency_group: elastic-agent-extended-testing/serverless-integration
  #   concurrency: 8
  #   env:
  #     # we run each step in a different data center to spread the load
  #     TEST_INTEG_AUTH_GCP_DATACENTER: "us-central1-a"
  #   command: ".buildkite/scripts/steps/integration_tests.sh serverless integration:single TestLogIngestionFleetManaged" #right now, run a single test in serverless mode as a sort of smoke test, instead of re-running the entire suite
  #   artifact_paths:
  #     - "build/TEST-**"
  #     - "build/diagnostics/*"
  #   agents:
  #     provider: "gcp"
  #     machineType: "n1-standard-8"
  #   notify:
  #     - github_commit_status:
  #         context: "buildkite/elastic-agent-extended-testing - Serverless integration test"

  # - label: "Extended runtime leak tests"
  #   key: "extended-integration-tests"
  #   concurrency_group: elastic-agent-extended-testing/leak-tests
  #   concurrency: 8
  #   env:
  #     TEST_INTEG_AUTH_GCP_DATACENTER: "us-central1-b"
  #   command: ".buildkite/scripts/steps/integration_tests.sh stateful integration:TestForResourceLeaks"
  #   artifact_paths:
  #     - "build/TEST-**"
  #     - "build/diagnostics/*"
  #   agents:
  #     provider: "gcp"
  #     machineType: "n1-standard-8"
  #   notify:
  #     - github_commit_status:
  #         context: "buildkite/elastic-agent-extended-testing - Extended runtime leak tests"

  # - label: "Integration tests"
  #   key: "integration-tests"
  #   concurrency_group: elastic-agent-extended-testing/integration
  #   concurrency: 8
  #   env:
  #     TEST_INTEG_AUTH_GCP_DATACENTER: "us-central1-f"
  #   command: ".buildkite/scripts/steps/integration_tests.sh stateful"
  #   artifact_paths:
  #     - "build/TEST-**"
  #     - "build/diagnostics/*"
  #   agents:
  #     provider: "gcp"
  #     machineType: "n1-standard-8"
  #   notify:
  #     - github_commit_status:
  #         context: "buildkite/elastic-agent-extended-testing - Integration tests"

  # - label: "Serverless Beats Tests"
  #   key: "serverless-beats-integration-tests"
  #   concurrency_group: elastic-agent-extended-testing/beats-integration
  #   concurrency: 8
  #   env:
  #     TEST_INTEG_AUTH_GCP_DATACENTER: "us-central1-a"
  #   command: ".buildkite/scripts/steps/beats_tests.sh"
  #   # if: "build.env('CRON') == 'yes'"
  #   agents:
  #     provider: "gcp"
  #     machineType: "n1-standard-8"
  #   retry:
  #     manual:
  #       allowed: true
  #   notify:
  #     - github_commit_status:
  #         context: "buildkite/elastic-agent-extended-testing - Serverless Beats Tests"
